services:
  timeserver:
    build:
      context: ./timeserver
      dockerfile: Containerfile
    ports:
      - "8080"
    environment:
      - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
      - FAKETIME_TIMESTAMP_FILE=/tmp/faketime
      - TZ=UTC
    volumes:
      - ./tmp/faketime:/tmp/faketime:ro
    networks:
      dst_net:
        ipv4_address: 172.28.0.10

  exim_send:
    build:
      context: ./exim
      dockerfile: Containerfile
    ports:
      - "25"
    volumes:
      - ./exim/send.conf:/etc/exim4/exim4.conf:ro
      - ./tmp/faketime:/tmp/faketime:ro
    environment:
      - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
      - FAKETIME_TIMESTAMP_FILE=/tmp/faketime
      - TZ=UTC
    networks:
      dst_net:
        ipv4_address: 172.28.0.20
    healthcheck:
      test: ["CMD", "exim4", "-bV"]
      interval: 1s
      timeout: 3s
      retries: 3
      start_period: 1s

  exim_receive:
    build:
      context: ./exim
      dockerfile: Containerfile
    volumes:
      - ./exim/receive.conf:/etc/exim4/exim4.conf:ro
      - ./tmp/mail:/var/mail
      - ./tmp/faketime:/tmp/faketime:ro
    environment:
      - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
      - FAKETIME_TIMESTAMP_FILE=/tmp/faketime
      - TZ=UTC
    networks:
      dst_net:
        ipv4_address: 172.28.0.30
    healthcheck:
      test: ["CMD", "exim4", "-bV"]
      interval: 1s
      timeout: 3s
      retries: 3
      start_period: 1s

networks:
  dst_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
