FROM python:3.9-slim
RUN apt-get update && apt-get install -y libfaketime && rm -rf /var/lib/apt/lists/*
COPY ./app.py /app.py
HEALTHCHECK --interval=1s --timeout=3s --start-period=1s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')" || exit 1
CMD ["python", "/app.py"]
