FROM debian:bullseye-slim

# Install Exim4 and required utilities
RUN apt-get update && apt-get install -y \
    exim4 \
    libfaketime \
    && rm -rf /var/lib/apt/lists/*

# Expose SMTP port
EXPOSE 25

# Create file to get around tainted values
# https://jimbobmcgee.wordpress.com/2020/07/29/de-tainting-exim-configuration-variables/
RUN echo '*' > /etc/exim4/detaint && \
    chmod 400 /etc/exim4/detaint && \
    chown Debian-exim /etc/exim4/detaint

# Remove setuid bit from Exim
# Else it won't load the LD_PRELOAD library since the ruid != euid
RUN chmod u-s /usr/sbin/exim4

USER Debian-exim

# Start Exim in foreground mode
CMD ["exim4", "-bd", "-q1m", "-v"]
